import { Metadata } from "next";
import ResetPasswordForm from "../../../components/root/ResetPasswordForm";

export const metadata: Metadata = {
  title: "Auth | Reset Password",
  description: "Generated by create next nexus app",
};

const page = () => {
  return (
    <div className="flex h-[100vh]">
      <ResetPasswordForm />
    </div>
  );
};

export default page;
