import type { Metadata } from "next";

import "../globals.css";
import { Lato } from "next/font/google";
import useToken from "@/hooks/use-token";
import Header from "./components/Header";
import QueryProvider from "@/hooks/QueryProvider";
import { Toaster } from "@/components/ui/toaster";

const lato = Lato({ subsets: ["latin"], weight: "400" });

export const dynamic = "force-dynamic";

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next nexus app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  const Token = useToken();
  const { sessionToken } = Token as { sessionToken: string };
  return (
    <html lang="en">
      <body className={`${lato.className}`}>
        <QueryProvider>
          <Header sessionToken={sessionToken} />
          {children}
          <Toaster />
        </QueryProvider>
      </body>
    </html>
  );
};

export default RootLayout;
