import "../globals.css";
import type { Metadata } from "next";
import { Lato } from "next/font/google";
import { Toaster } from "@/components/ui/toaster";

const lato = Lato({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "Auth",
  description: "Generated by create next nexus app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en">
      <body className={lato.className}>
        {children}
        <Toaster />
      </body>
    </html>
  );
};

export default RootLayout;
