import { Metadata } from "next";
import useToken from "@/hooks/use-token";
import MailConfigForm from "@/app/(dashboard)/components/root/MailConfigForm";

export const metadata: Metadata = {
  title: "Dashboard | Mail",
  description: "Generated by create next nexus app",
};

const page = () => {
  const Token = useToken();
  const { sessionToken } = Token as { sessionToken: string };

  return (
    <div className="flex h-[100vh]">
      <MailConfigForm sessionToken={sessionToken} />;
    </div>
  );
};

export default page;
