import { Metadata } from "next";
import useToken from "@/hooks/use-token";
import ViewUserForm from "@/app/(dashboard)/components/root/ViewUserForm";

export const metadata: Metadata = {
  title: "Dashboard | User",
  description: "Generated by create next nexus app",
};

const page = () => {
  const Token = useToken();
  const { sessionToken } = Token as { sessionToken: string };

  return <ViewUserForm sessionToken={sessionToken} />;
};

export default page;
