import { Metadata } from "next";
import RegisterForm from "@/app/(auth)/components/root/RegisterForm";

export const metadata: Metadata = {
  title: "Auth | Register",
  description: "Generated by create next nexus app",
};

const page = () => {
  return (
    <div className="flex h-[100vh]">
      <RegisterForm />
    </div>
  );
};

export default page;
