import { Metadata } from "next";
import ForgotPasswordForm from "../../components/root/ForgotPasswordForm";

export const metadata: Metadata = {
  title: "Auth | Forgot Password",
  description: "Generated by create next nexus app",
};

const page = () => {
  return (
    <div className="flex h-[100vh]">
      <ForgotPasswordForm />
    </div>
  );
};

export default page;
