import { Metadata } from "next";
import useToken from "@/hooks/use-token";
import Users from "@/app/(dashboard)/components/root/Users";

export const metadata: Metadata = {
  title: "Dashboard | Users",
  description: "Generated by create next nexus app",
};

const page = async () => {
  const Token = useToken();
  const { sessionToken } = (await Token) as { sessionToken: string };
  return <Users sessionToken={sessionToken} />;
};

export default page;
